- client: !!python/object/new:p2psimpy.config.PeerType
  - PeerConfig:
      bandwidth_dl:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      bandwidth_ul:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      location:
        Dist:
          name: sample
          params: '[''Ohio'', ''Ireland'', ''Tokyo'']'
  - BaseConnectionManager: null
    ConflictMessageProducer:
      MsgConfig:
        pre_task: !!python/name:__main__.validate_task ''
  peer: !!python/object/new:p2psimpy.config.PeerType
  - PeerConfig:
      bandwidth_dl:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      bandwidth_ul:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      location:
        Dist:
          name: sample
          params: '[''Ohio'', ''Ireland'', ''Tokyo'']'
  - BaseConnectionManager: null
    Consensus: null
    Consensus2: null
    PullGossipService:
      GossipConfig:
        exclude_types: !!set
          bootstrap: null
          client: null
    RandomDowntime:
      DowntimeConfig:
        disruption_intervals:
          DistAttr:
            name: norm
            params: (200, 100)
        disruption_time:
          DistAttr:
            name: norm
            params: (800, 200)
        start_time:
          DistAttr:
            name: norm
            params: (1500, 200)
- BaseConnectionManager: !!python/name:p2psimpy.services.connection_manager.BaseConnectionManager ''
  ConflictMessageProducer: !!python/name:__main__.ConflictMessageProducer ''
  Consensus: !!python/name:__main__.Consensus ''
  Consensus2: !!python/name:__main__.Consensus2 ''
  PullGossipService: !!python/name:p2psimpy.services.gossip.PullGossipService ''
  RandomDowntime: !!python/name:p2psimpy.services.disruption.RandomDowntime ''
